book:
  title: "Building reproducible books with Bioconductor (template)"
  chapters:
    - index.qmd
    - pages/preamble.qmd
    - part: "Part 1"
      chapters: 
        - pages/Part-1/Chapter-1.qmd
        - pages/Part-1/Chapter-2.qmd
  page-footer:
    left: |
      This book was built <a href="https://github.com/js2264/BiocBook/">BiocBook</a> with ❤️.
  cover-image: inst/assets/cover.jpg
  site-url: https://js2264.github.io/BiocBook.template/
  repo-url: https://github.com/js2264/BiocBook.template/
  repo-branch: devel
  repo-actions: [edit, issue]

project:
  type: book
  output-dir: docs

format:
  html:
    grid:
      sidebar-width: 350px
    theme:
      - inst/assets/book.scss
    highlight-style: atom-one
    code-link: true
    citations-hover: true
    toc: true
    toc-float: 
      collapsed: false
    toc-depth: 3
    website: 
      sidebar: 
        search: true
        collapse-level: 5

editor: visual
reference-section-title: References
bibliography: inst/assets/bibliography.bib
filters:
  - inst/extensions/pandoc-ext/section-bibliographies/section-bibliographies.lua
