## --- Project-wide settings
project:
  type: book
  output-dir: docs

metadata-files:
  - assets/_book.yml
  - assets/_website.yml

## --- Format options
format: 
  html:
    grid:
      sidebar-width: 500px
      body-width: 800px
    theme: 
      - cosmo
      - assets/book.scss
    highlight-style: atom-one
    code-link: true
    editor: visual
    citation-location: margin
    bibliography: assets/bibliography.bib
    from: markdown+emoji

## --- knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "## " 
    cache: false
    fig.align: "center"
    python.reticulate: false
    R.options:
      dplyr.print_min: 6
      dplyr.print_max: 6
      pillar.max_footer_lines: 2
      pillar.min_chars: 15
      stringr.view_n: 6
      pillar.bold: TRUE
      width: 77 # 80 - 3 for #> comments

## --- Additional lua filters 
filters:
  - extensions/tools-tabset-ext/tools-tabset.lua